---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

- name: setup load_balancer tier and some basic conf
  hosts: frontends
  become: yes
  roles:
    - base_config
    - load_balancer

- name: setup app_server
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - app_server

- name: install database tier
  become: yes  
  hosts: appdbs
  roles: 
    - geerlingguy.postgresql
